services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "*#Samrat21"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "referrer-db"
    volumes:
      - "D:/Documents/volume/referrer-db:/var/lib/postgresql/data"
    networks:
      - referrer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: referrer-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./root/.env
    environment:
      ENVIRONMENT: "development"
    networks:
      - referrer
    # entrypoint: ["/app/scripts/server.sh"]

networks:
  referrer:
    driver: bridge