# Generated by Django 5.1.4 on 2025-01-05 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('job_description', models.TextField()),
                ('experience', models.PositiveIntegerField(verbose_name='Experience in years')),
                ('salary', models.PositiveIntegerField(verbose_name='Salary in LPA')),
                ('expiry_date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('applied_by', models.ManyToManyField(blank=True, related_name='applied_to', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='skills', to='skills.skills')),
            ],
        ),
    ]
