# Generated by Django 5.1.2 on 2024-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
