name: Referrer Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Fetch and Create Environment Files
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.FRONTEND_SERVICE_ID }}
        run: |
          echo "Fetching secret file from Render API..."
          if ! SECRET_CONTENT=$(curl -s -f -H "Authorization: Bearer $RENDER_API_KEY" \
            "https://api.render.com/v1/services/$SERVICE_ID/secret-files" \
            | jq -r '.[0].secretFile.content'); then
            echo "Failed to fetch secrets from Render API"
            exit 1
          fi

          echo "Creating .env.production file..."
          echo "$SECRET_CONTENT" > frontend/.env.production

          echo "Verifying .env.production was created:"
          ls -la frontend/.env.production
          echo "Environment file created successfully"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/referrer-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: curl -X POST https://api.render.com/deploy/${{secrets.FRONTEND_SERVICE_ID}}?key=${{ secrets.FRONTEND_RENDER_DEPLOY_HOOK }}
