name: Referrer Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract Environment Variables
        id: env-vars
        run: |
          echo "Fetching secret file from Render API..."
          if ! SECRET_CONTENT=$(curl -s -f -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            "https://api.render.com/v1/services/${{ secrets.FRONTEND_SERVICE_ID }}/secret-files" \
            | jq -r '.[0].secretFile.content'); then
            echo "Failed to fetch secrets from Render API"
            exit 1
          fi

          while read -r line; do
            if [[ $line == NEXT_PUBLIC_* ]]; then
              key=$(echo "$line" | cut -d'=' -f1 | xargs)
              value=$(echo "$line" | cut -d'=' -f2- | sed 's/^[[:space:]]*"//;s/"[[:space:]]*$//')
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done <<< "$SECRET_CONTENT"

      - name: Build Environment File
        run: |
          cd frontend
          touch .env.production
          
          # Use the environment variables
          echo "NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}" >> .env.production
          echo "NEXT_PUBLIC_MEDIA_LIBRARY_URL=${{ env.NEXT_PUBLIC_MEDIA_LIBRARY_URL }}" >> .env.production
          echo "NEXT_PUBLIC_GRAPHQL_URL=${{ env.NEXT_PUBLIC_GRAPHQL_URL }}" >> .env.production

      - name: Build and Push Docker Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/referrer-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/referrer-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: curl -X POST https://api.render.com/deploy/${{secrets.FRONTEND_SERVICE_ID}}?key=${{ secrets.FRONTEND_RENDER_DEPLOY_HOOK }}
